package droidco.west3.ironsight.npc;

public enum NPCType {
  SHOPKEEPER,
  ARMS_DEALER,
  OFFICER_ARMS_DEALER,
  ILL_ARMS_DEALER,
  FISHERMAN,
  PHARMACIST,
  ARMORER,
  ILLEGAL_ARMORER,
  GEOLOGIST,
  STABLE_MANAGER,
  CONDUCTOR,
  FERRY_CAPTAIN,
  BANKER,
  VAULT_KEEPER,
  CONTRACTOR,
  CHIEF_OF_POLICE,
  DRUG_PROCESSOR,
  SUPER_PROCESSOR,

  OIL_PROCESSOR,
}
