name: IronSight
version: '${version}'
main: droidco.west3.ironsight.IronSight
api-version: '1.20'
commands:
  ironsight:
    aliases:
      - is
  stats:
  contract:
    aliases:
      - c
  give_common:
    aliases:
      - g_c
  get_item:
    aliases:
      - g_i
