package droidco.west3.ironsight.Contracts;

import droidco.west3.ironsight.Bandit.Bandit;
import droidco.west3.ironsight.Contracts.Utils.CompletionStep;
import droidco.west3.ironsight.Items.ItemIcon;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Item;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.ArrayList;
import java.util.List;

public class OpenContractUI
{


    public static Inventory openActiveContractUi(Player p, Contract contract){
        Inventory contractUi = Bukkit.createInventory(p, 54, ChatColor.DARK_GRAY+"Active Contract info:");
        Bandit iPlayer = Bandit.getPlayer(p);
        int reqColumn = 4;
        int locColumn = 2;
        int descColumn = 6;


        contractUi.setItem(locColumn, ItemIcon.getIcon("contractLoc").getItem());
        contractUi.setItem(reqColumn,ItemIcon.getIcon("contractReq").getItem());
        contractUi.setItem(descColumn,ItemIcon.getIcon("contractDesc").getItem());
        //the rest of the slots are auto generated by the steps list
        List<CompletionStep> steps = contract.getSteps();
        for(CompletionStep step : steps){
            locColumn += 9;
            reqColumn +=9;
            descColumn +=9;
            int stepNum = step.getStepNumber();
            ItemStack locSlot = getStepLocationIcon(stepNum,step.getLocationDesc());
            ItemStack descSlot = getStepDescIcon(stepNum,step.getTaskDesc());
            ItemStack reqSlot = getStepRequesteditem(stepNum,step.getRequestedGoods());
            contractUi.setItem(locColumn, ItemIcon.getIcon("contractLoc").getItem());
            contractUi.setItem(reqColumn,ItemIcon.getIcon("contractReq").getItem());
            contractUi.setItem(descColumn,ItemIcon.getIcon("contractDesc").getItem());
        }

        //contractUi.setItem(11,getResignContractIcon());
        //contractUi.setItem(13,getActiveContractItem(iPlayer));
        return contractUi;
    }
    public static ItemStack getStepDescIcon(int stepNumber, List<String> stepDesc){
        ItemStack item = new ItemStack(Material.BOOK);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("Step "+stepNumber);
        for (String step : stepDesc){
            step = String.valueOf(ChatColor.GRAY)+step;
        }
        meta.setLore(stepDesc);
        item.setItemMeta(meta);
        return item;
    }
    public static ItemStack getStepLocationIcon(int stepNumber, String stepLoc){
        ItemStack item = new ItemStack(Material.COMPASS);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("Step "+stepNumber);
        List<String> lore = new ArrayList<>();
        lore.add(String.valueOf(ChatColor.GRAY)+stepLoc);
        meta.setLore(lore);
        item.setItemMeta(meta);
        return item;
    }
    public static ItemStack getStepRequesteditem(int stepNumber, ItemStack requestedItem){
        ItemStack item = new ItemStack(Material.DIAMOND);
        ItemMeta meta = item.getItemMeta();
        meta.setDisplayName("Step "+stepNumber);
        List<String> lore = new ArrayList<>();
        if(requestedItem != null){
            int amount = requestedItem.getAmount();
            String requestMessage = String.valueOf(ChatColor.GRAY)+"Aqcuire "+amount+requestedItem.getItemMeta().getDisplayName();
            lore.add(requestMessage);
        }
        meta.setLore(lore);
        item.setItemMeta(meta);
        return item;
    }
}
