name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Repository Cache
        uses: TheRealRyGuy/clear-cache-action@master
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
      - name: Build with Gradle
        run: gradle shadowJar